src/Entity/Wish.php
<?php

namespace App\Entity;

use App\Repository\WishRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: WishRepository::class)]
class Wish
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\Length(min: 4, max: 255)]
    #[ORM\Column(length: 250)]
    private ?string $title = null;

    #[Assert\NotBlank]
    #[Assert\Length(min: 10, max: 255)]
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[Assert\Length(min: 3, max: 255)]
    #[ORM\Column(length: 50)]
    private ?string $author = null;

    #[ORM\Column(options: ['default' => false])]
    private ?bool $isPublished = false;

    #[ORM\Column]
    private ?\DateTimeImmutable $dateCreated = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $dateUpdate = null;

    #[ORM\ManyToOne(inversedBy: 'wishes')]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): static
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeImmutable
    {
        return $this->dateCreated;
    }

    public function setDateCreated(\DateTimeImmutable $dateCreated): static
    {
        $this->dateCreated = $dateCreated;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeImmutable
    {
        return $this->dateUpdate;
    }

    public function setDateUpdate(?\DateTimeImmutable $dateUpdate): static
    {
        $this->dateUpdate = $dateUpdate;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/WishType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Wish;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WishType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('author')
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Wish::class,
        ]);
    }
}

src/Controller/WishController.php
<?php

namespace App\Controller;

use App\Entity\Wish;
use App\Form\WishType;
use App\Repository\WishRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class WishController extends AbstractController
{
    #[Route('/wishes', name: 'wish_list')]
    public function list(WishRepository $wishRepository): Response
    {
        $wishes = $wishRepository->findAll();

        return $this->render('wish/list.html.twig', [
            'wishes' => $wishes,
        ]);
    }

    #[Route('/wishes/{id}', name: 'wish_detail', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function detail(int $id, WishRepository $wishRepository): Response
    {
        $wish = $wishRepository->find($id);

        if(!$wish){
            throw $this->createNotFoundException("Le souhait n'existe pas.");
        }

        return $this->render('wish/detail.html.twig', [
            'wish' => $wish,
        ]);
    }

    #[Route('/wish-create', name: 'wish_create', methods: ['GET', 'POST'])]
    public function create(Request $request, EntityManagerInterface $em): Response
    {
        $wish = new Wish();

        $form = $this->createForm(WishType::class, $wish);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Publié par défaut
            $wish->setIsPublished(true);
            // Date = Now
            $wish->setDateCreated(new \DateTimeImmutable("now"));

            $em->persist($wish);
            $em->flush();

            $this->addFlash("success", "Le voeux a été crée avec succès");

            return $this->redirectToRoute('wish_detail', ['id' => $wish->getId()]);
        }

        return $this->render('wish/create.html.twig', [
            'wishForm' => $form->createView(),
        ]);
    }


}

templates/wish/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }} | Créer un voeux
{% endblock %}

{% block body %}
    <h1>Create Wish</h1>

    {# Ouvrir le formulaire #}
    {{ form_start(wishForm) }}

    {# Afficher tout les champs #}
    {{ form_widget(wishForm) }}

    <div class="uk-margin">
        <button type="submit" class="uk-button uk-button-primary uk-width-1-1 uk-margin-small-bottom">Save</button>
    </div>

    {# Fermer le formulaire #}
    {{ form_end(wishForm) }}
{% endblock %}

templates/wish/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Détail | {{ parent() }}
{% endblock %}

{% block body %}

    <h2>{{ wish.title }}</h2>
    <p>{{ wish.description }}</p>
    <p>Auteur : {{ wish.author }}</p>
    <p>Publié : {{ wish.published ? 'Oui' : 'Non' }}</p>
    <p>Date de création : {{ wish.dateCreated | date('d/m/Y') }}</p>
    <p>Category: {{ wish.category ? wish.category.name : 'Aucune catégorie' }}</p>

{% endblock %}

templates/wish/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello WishController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>D:/wamp64/www/bucket-list/src/Controller/WishController.php</code></li>
        <li>Your template at <code>D:/wamp64/www/bucket-list/templates/wish/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/wish/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>All Wishes</h2>

<div class="uk-child-width-1-2@s uk-grid-match" uk-grid>

        {% for w in wishes %}
            <div>
                <a href="{{ path('wish_detail', {'id': w.id}) }}">
                <div class="uk-card uk-card-hover uk-card-body eni-card">
                    <h3 class="uk-card-title">{{ w.title }}</h3>
                    <p>Category: {{ w.category ? w.category.name : 'Aucune catégorie' }}</p>
                    <p>Read more</p>
                </div>
                </a>
            </div>
        {% endfor %}
</div>


{% endblock %}

{% block title %}
    All wishes | {{ parent() }}
{% endblock %}